server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/bankdb}
    username: ${DB_USERNAME:bank}
    password: ${DB_PASSWORD:bank}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:dev-jwt-secret-change-me}
    ttl-ms: ${JWT_TTL_MS:3600000}
  card:
    aesSecret: ${CARD_AES_SECRET:change-me-32-bytes-change-me-32-bytes}