spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bankdb}
    username: ${DB_USERNAME:bank}
    password: ${DB_PASSWORD:bank}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  liquibase:
    change-log: classpath:db/migration/master.xml

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:dev-jwt-secret-change-me}
    ttl-ms: ${JWT_TTL_MS:3600000}
